export const FETCH_GOALS = 'FETCH_GOALS';
export const NEW_GOAL = 'NEW_GOAL';
export const COMPLETE_TYPE1_GOAL = 'COMPLETE_TYPE1_GOAL';
export const COMPLETE_TYPE2_GOAL = 'COMPLETE_TYPE2_GOAL';
export const DELETE_GOAL = 'DELETE_GOAL';
export const CHANGE_GOAL = 'CHANGE_GOAL';
